.TH "Lab10/src/Lab10/Task3/Debug Directory Reference" 3 "Version 0.1" "Lab10 Climate Sensor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lab10/src/Lab10/Task3/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclimate_monitor\&.d\fP"
.br
.ti -1c
.RI "file \fBmain\&.d\fP"
.br
.ti -1c
.RI "file \fBscd41\&.d\fP"
.br
.ti -1c
.RI "file \fBserlcd\&.d\fP"
.br
.in -1c
