.TH "Lab10/src/Lab10/Task3 Directory Reference" 3 "Version 0.1" "Lab10 Climate Sensor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lab10/src/Lab10/Task3 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclimate_monitor\&.c\fP"
.br
.ti -1c
.RI "file \fBscd41\&.c\fP"
.br
.ti -1c
.RI "file \fBscd41\&.h\fP"
.br
.RI "Interface for interacting with the SCD41 CO? sensor via I2C\&. "
.ti -1c
.RI "file \fBserlcd\&.c\fP"
.br
.ti -1c
.RI "file \fBserlcd\&.h\fP"
.br
.in -1c
