.TH "D:/ESE381/Lab06/src/Task2 Directory Reference" 3 "Version 0" "Lab07" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/ESE381/Lab06/src/Task2 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlm75\&.c\fP"
.br
.ti -1c
.RI "file \fBlm75\&.h\fP"
.br
.ti -1c
.RI "file \fBserlcd\&.c\fP"
.br
.ti -1c
.RI "file \fBserlcd\&.h\fP"
.br
.ti -1c
.RI "file \fBtemp_meas_LM75\&.c\fP"
.br
.in -1c
