spi0.h
void init_spi0(void)
Initializes SPI0 to master-only mode. None None
void init_spi0_SerLCD(void)
Initializes SPI0 to be compatible with the SerLCD. None None
void init_spi0_LM74(void)
Initializes SPI0 to be compatible with the LM74. None None
uint16_t read_spi0_LM74(void)
Reads two bytes from an LM74 via SPI0 and returns the 16-bit response. None LM74 output.
References deselect_slave_LM74, exchange_byte, select_slave_LM74.
void send_byte_SerLCD(uint8_t data)
Sends a byte out of SPI0. Assumes /SS = PA7. data Byte to be sent. None
References deselect_slave_SerLCD, exchange_byte, select_slave_SerLCD.
Referenced by set_backlight_rgb.
void select_slave_SerLCD()
Pulls PA3 low. None None
Referenced by send_byte_SerLCD.
void deselect_slave_SerLCD()
Pulls PA3 high. None None
Referenced by send_byte_SerLCD.
void select_slave_LM74()
Pulls PA7 low. None None
Referenced by read_spi0_LM74.
void deselect_slave_LM74()
Pulls PA7 high. None None
Referenced by read_spi0_LM74.
uint8_t exchange_byte(uint8_t data)
Sends and receives one byte from SPI0. Does not automatically select/deselect slave device. data Data to be sent. Data in SPI0.DATA after exchange.
Referenced by read_spi0_LM74, send_byte_SerLCD.
uint8_t normalize_range(uint8_t from_min, uint8_t from_val, uint8_t from_max, uint8_t result_min, uint8_t result_max)
(This function should not be here, but I am too lazy. Whatever.) Normalizes a uint8_t to another range. from_min Minimum value of original range. from_val Value to normalize. from_max Maximum value of original range. result_min Minimum value of normalized range. result_max Maximum value of normalized range. Normalized number.
Referenced by set_backlight_rgb.
void set_backlight_rgb(uint8_t r, uint8_t g, uint8_t b)
Normalizes r, g, b to be between 0-29 (inclusive) and sends the sequence |r|g|b r Red. 0 to 255. g Green. 0 to 255. b Blue. 0 to 255. None
References normalize_range, send_byte_SerLCD.