twi0_master.c
TWI_READ
Adapted by Mingi Hwang on 24 Mar 2025 from original source: https://github.com/microchip-pic-avr-examples/avr128db48-bare-metal-twi-mplab/tree/master/twi-host.X/peripherals/TWI ORIGINAL SOURCE LICENSE STATEMENT (c) 2020 Microchip Technology Inc. and its subsidiaries. Subject to your compliance with these terms, you may use Microchip software and any derivatives exclusively with Microchip products. You're responsible for complying with 3rd party license terms applicable to your use of 3rd party software (including open source software) that may accompany Microchip software. SOFTWARE IS "AS IS." NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
Referenced by TWI_readByte, TWI_readBytes, TWI_sendAndReadBytes.
TWI_WRITE
Referenced by TWI_sendAndReadBytes, TWI_sendByte, TWI_sendBytes.
TWI_IS_CLOCKHELD
TWI_IS_BUSERR
TWI_IS_ARBLOST
CLIENT_NACK
Referenced by _writeToTWI.
CLIENT_ACK
TWI_IS_BUSBUSY
Referenced by _startTWI, isTWIBad.
TWI_WAIT
Referenced by _readFromTWI, _startTWI, _writeToTWI, TWI_sendAndReadBytes.
bool isTWIBad(void)
References TWI_IS_BUSBUSY.
Referenced by _startTWI, TWI_sendAndReadBytes.
void TWI_initHost(void)
Adapted by Mingi Hwang on 24 Mar 2025 from original source: https://github.com/microchip-pic-avr-examples/avr128db48-bare-metal-twi-mplab/tree/master/twi-host.X/peripherals/TWI ORIGINAL SOURCE LICENSE STATEMENT (c) 2020 Microchip Technology Inc. and its subsidiaries. Subject to your compliance with these terms, you may use Microchip software and any derivatives exclusively with Microchip products. You're responsible for complying with 3rd party license terms applicable to your use of 3rd party software (including open source software) that may accompany Microchip software. SOFTWARE IS "AS IS." NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE. Prof. Short does not want us to use internal pull-ups. External 10k PURs will be used. If defined, internal pull-up resistors will be used Initializes the TWI peripheral in Host Mode.
void TWI_initPins(void)
Initializes the I/O used by the TWI peripheral.
bool _startTWI(uint8_t addr, bool read)
References isTWIBad, TWI_IS_BUSBUSY, TWI_WAIT.
Referenced by TWI_readByte, TWI_readBytes, TWI_sendAndReadBytes, TWI_sendByte, TWI_sendBytes.
void _readFromTWI(uint8_t *data, uint8_t len)
References TWI_WAIT.
Referenced by TWI_readByte, TWI_readBytes, TWI_sendAndReadBytes.
bool _writeToTWI(uint8_t *data, uint8_t len)
References CLIENT_NACK, TWI_WAIT.
Referenced by TWI_sendAndReadBytes, TWI_sendByte, TWI_sendBytes.
bool TWI_sendByte(uint8_t addr, uint8_t data)
addr - Client Device Address data - Data to Send Sends a byte of data to the specified address. Returns true if successful, false if it failed
References _startTWI, _writeToTWI, TWI_WRITE.
bool TWI_sendBytes(uint8_t addr, uint8_t *data, uint8_t len)
addr - Client Device Address data - Pointer to the data to send len - Number of Bytes to Send Attempts to send len bytes of data to the client. Returns true if successful, false if it failed
References _startTWI, _writeToTWI, TWI_WRITE.
bool TWI_readByte(uint8_t addr, uint8_t *data)
addr - Client Device Address data - Where the byte received should be stored Attempts to read 1 byte of data from the client. Returns true if successful, fails if unable to get data.
References _readFromTWI, _startTWI, TWI_READ.
bool TWI_readBytes(uint8_t addr, uint8_t *data, uint8_t len)
addr - Client Device Address data - Where the bytes received should be stored len - Number of Bytes to Send Attempts to read len bytes of data from the client. Returns true if successful, false if it failed to get data.
References _readFromTWI, _startTWI, TWI_READ.
bool TWI_sendAndReadBytes(uint8_t addr, uint8_t regAddress, uint8_t *data, uint8_t len)
addr - Client Device Address regAddress - Address of Register to Read From data - Where the bytes received should be stored len - Number of Bytes to Send Writes a single byte (regAddress) to the client, then restarts and attempts to read len of data. Returns true if successful, false if it failed to get data.
References _readFromTWI, _startTWI, _writeToTWI, isTWIBad, TWI_READ, TWI_WAIT, TWI_WRITE.