usart3.h
void USART3_init(void)
Initializes USART3 to 9600 8N1 and sets the pin directions.
uint8_t USART3_read(void)
Blockingly reads a byte from USART3 by polling the RXCIF flag. None Byte read from USART3.
void USART3_send_char(uint8_t c)
Blockingly sends a byte out of USART3 by polling the DREIF flag. c Byte to be sent. None
Referenced by USART3_send_string, USART3_serlcd_backlight, USART3_serlcd_clear.
void USART3_send_string(const char *buf)
Blockingly sends a null-terminated ASCII string out of USART3 by calling USART3_send_char multiple times. buf Pointer to char array to be sent. None
References USART3_send_char.
void USART3_serlcd_clear(void)
Blockingly sends the sequence |- out of USART3 to clear a SparkFun SerLCD. None None
References USART3_send_char.
void USART3_serlcd_backlight(uint8_t r, uint8_t g, uint8_t b)
Blockingly sends the sequence +rgb to control the backlight RGB value on an RGB SparkFun SerLCD. r Red. 0 to 255. g Green. 0 to 255. b Blue. 0 to 255. None
References USART3_send_char.