.TH "D:/ESE381/Global/ese381/ese381/ascii.h" 3 "Version 0" "ESE 381 Module Drivers Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/ESE381/Global/ese381/ese381/ascii.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBcomplement_case\fP (uint8_t c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t complement_case (uint8_t c)"
Toggles capitalization of an ASCII character\&. All other characters are not affected\&. Example: a becomes A, R becomes r, { becomes {\&.

.PP
\fBParameters\fP
.RS 4
\fIc\fP Character to toggle the capitalization of\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Resulting character\&. 
.RE
.PP

.PP
Definition at line \fB3\fP of file \fBascii\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ESE 381 Module Drivers Library from the source code\&.
