scd41.c
const uint8_t start_meas[2][2]
const uint8_t read_meas[2][2]
const uint8_t stop_meas[2][2]
const uint8_t data_ready[2][2]
void scd41_start_periodic_meas(uint8_t addr)
Sends command to start periodic measurements on the SCD41. addr I2C address of the SCD41 sensor. None
Referenced by main.
void scd41_stop_periodic_meas(uint8_t addr)
Sends command to stop periodic measurements on the SCD41. addr I2C address of the SCD41 sensor. None
uint8_t scd41_has_data(uint8_t addr)
Checks if new measurement data is available from the SCD41. addr I2C address of the SCD41 sensor. 1 if data is ready, 0 otherwise.
Referenced by main.
scd41_data_t scd41_read_data(uint8_t addr)
Reads the latest measurement from the SCD41. addr I2C address of the SCD41 sensor. scd41_data_t struct containing raw values, CRCs, and converted temperature and humidity.
References scd41_data_t::co2_crc, scd41_data_t::co2_raw, scd41_data_t::rh, scd41_data_t::rh_crc, scd41_data_t::rh_raw, scd41_data_t::temp_c, scd41_data_t::temp_c_crc, scd41_data_t::temp_c_raw.
Referenced by main.