serlcd.h
F_CPU
TWI_SERLCD_INTERVAL_US
Referenced by clear_SerLCD, send_string_SerLCD, serlcd_set_background_rgb, turn_backlight_off.
SERLCD_ROWS
Referenced by update_SerLCD.
SERLCD_COLS
Referenced by update_SerLCD.
char serlcd_buffer[SERLCD_ROWS][SERLCD_COLS+1][SERLCD_ROWS][SERLCD_COLS+1]
The 4x20 character buffer for the SerLCD.
Referenced by fill_buffer, initializing, update_SerLCD.
void send_string_SerLCD(uint8_t addr, uint8_t *str, uint8_t len)
Sends char array to the SerLCD out of TWI0. addr I2C slave address of the SerLCD. str Pointer to start of char array to be sent. len Length of char array. None
References TWI_SERLCD_INTERVAL_US.
Referenced by update_SerLCD.
void clear_SerLCD(uint8_t addr)
Sends the byte sequence |- out of TWI0 to clear the SerLCD. addr I2C slave address of the SerLCD. None
References TWI_SERLCD_INTERVAL_US.
Referenced by update_SerLCD.
void update_SerLCD(uint8_t addr)
Sends contents of serlcd_buffer out of TWI0. addr I2C slave address of the SerLCD. None
References clear_SerLCD, send_string_SerLCD, serlcd_buffer, SERLCD_COLS, SERLCD_ROWS.
Referenced by main.
void turn_backlight_off(uint8_t addr)
Sends byte sequence to turn off the SerLCD backlight. addr I2C slave address of the SerLCD. None
References TWI_SERLCD_INTERVAL_US.
Referenced by main.
void serlcd_set_background_rgb(uint8_t addr, uint8_t r, uint8_t g, uint8_t b)
Sets the RGB background color of the SerLCD backlight. addr I2C slave address of the SerLCD. r Red intensity (0–255). g Green intensity (0–255). b Blue intensity (0–255). None
References TWI_SERLCD_INTERVAL_US.